-- Complete movie database with all categories and metadata
-- This replaces all the scattered seed files with one comprehensive dataset

TRUNCATE TABLE movies;

INSERT INTO movies (
    title, 
    description, 
    release_year, 
    rating, 
    image_url, 
    trailer_url, 
    youtube_trailer_id,
    video_url,
    genres,
    director,
    movie_cast,
    duration,
    content_type,
    keywords,
    categories
) VALUES 

-- TRENDING MOVIES
(
    'The Matrix',
    'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    1999,
    8.7,
    'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    'vKQi3bBA1y8',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    ARRAY['Action', 'Sci-Fi'],
    'Lana Wachowski, Lilly Wachowski',
    ARRAY['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
    136,
    'movie',
    ARRAY['matrix', 'reality', 'simulation', 'neo', 'morpheus'],
    ARRAY['trending', 'scifi']
),
(
    'Inception',
    'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    2010,
    8.8,
    'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    'https://www.youtube.com/watch?v=YoHD9XEInc0',
    'YoHD9XEInc0',
    'https://www.youtube.com/watch?v=YoHD9XEInc0',
    ARRAY['Action', 'Sci-Fi', 'Thriller'],
    'Christopher Nolan',
    ARRAY['Leonardo DiCaprio', 'Marion Cotillard', 'Tom Hardy', 'Ellen Page'],
    148,
    'movie',
    ARRAY['dreams', 'inception', 'subconscious', 'heist'],
    ARRAY['trending', 'scifi']
),
(
    'The Dark Knight',
    'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    2008,
    9.0,
    'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    'EXeTwQWrcwY',
    'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    ARRAY['Action', 'Crime', 'Drama'],
    'Christopher Nolan',
    ARRAY['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'],
    152,
    'movie',
    ARRAY['batman', 'joker', 'gotham', 'superhero'],
    ARRAY['trending', 'popular']
),
(
    'Interstellar',
    'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
    2014,
    8.6,
    'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    'zSWdZVtXT7E',
    'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    ARRAY['Sci-Fi', 'Drama', 'Adventure'],
    'Christopher Nolan',
    ARRAY['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    169,
    'movie',
    ARRAY['space', 'wormhole', 'time', 'survival'],
    ARRAY['trending', 'scifi']
),

-- POPULAR MOVIES
(
    'Pulp Fiction',
    'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    1994,
    8.9,
    'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    's7EdQ4FqbhY',
    'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    ARRAY['Crime', 'Drama'],
    'Quentin Tarantino',
    ARRAY['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis'],
    154,
    'movie',
    ARRAY['crime', 'violence', 'redemption', 'tarantino'],
    ARRAY['popular', 'classics']
),
(
    'Fight Club',
    'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
    1999,
    8.8,
    'https://image.tmdb.org/t/p/w500/a26cQPRhJPX6GbWfQbvZdrrp9j9.jpg',
    'https://www.youtube.com/watch?v=qtRKdVHc-cE',
    'qtRKdVHc-cE',
    'https://www.youtube.com/watch?v=qtRKdVHc-cE',
    ARRAY['Drama', 'Thriller'],
    'David Fincher',
    ARRAY['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    139,
    'movie',
    ARRAY['fight', 'club', 'society', 'rebellion'],
    ARRAY['popular']
),
(
    'Goodfellas',
    'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.',
    1990,
    8.7,
    'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    'vKQi3bBA1y8',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    ARRAY['Crime', 'Drama'],
    'Martin Scorsese',
    ARRAY['Robert De Niro', 'Ray Liotta', 'Joe Pesci', 'Lorraine Bracco'],
    146,
    'movie',
    ARRAY['mob', 'mafia', 'crime', 'scorsese'],
    ARRAY['popular', 'classics']
),
(
    'The Godfather',
    'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    1972,
    9.2,
    'https://image.tmdb.org/t/p/w500/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg',
    'https://www.youtube.com/watch?v=UaVTIH8mujA',
    'UaVTIH8mujA',
    'https://www.youtube.com/watch?v=UaVTIH8mujA',
    ARRAY['Crime', 'Drama'],
    'Francis Ford Coppola',
    ARRAY['Marlon Brando', 'Al Pacino', 'James Caan', 'Diane Keaton'],
    175,
    'movie',
    ARRAY['godfather', 'mafia', 'family', 'power'],
    ARRAY['popular', 'classics']
),

-- SCI-FI MOVIES
(
    'Blade Runner 2049',
    'A young blade runner''s discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who''s been missing for thirty years.',
    2017,
    8.0,
    'https://image.tmdb.org/t/p/w500/aMpyrCizvSdc0UIMblJ1srVgAEF.jpg',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    'vKQi3bBA1y8',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    ARRAY['Sci-Fi', 'Thriller'],
    'Denis Villeneuve',
    ARRAY['Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Jared Leto'],
    164,
    'movie',
    ARRAY['blade runner', 'replicant', 'future', 'android'],
    ARRAY['scifi']
),
(
    'Dune',
    'Feature adaptation of Frank Herbert''s science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.',
    2021,
    8.0,
    'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
    'https://www.youtube.com/watch?v=n9xhJrPXop4',
    'n9xhJrPXop4',
    'https://www.youtube.com/watch?v=n9xhJrPXop4',
    ARRAY['Sci-Fi', 'Adventure', 'Drama'],
    'Denis Villeneuve',
    ARRAY['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac', 'Josh Brolin'],
    155,
    'movie',
    ARRAY['dune', 'spice', 'desert', 'prophecy'],
    ARRAY['scifi', 'modernBlockbusters']
),
(
    'Arrival',
    'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
    2016,
    7.9,
    'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    'vKQi3bBA1y8',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    ARRAY['Sci-Fi', 'Adventure', 'Drama'],
    'Denis Villeneuve',
    ARRAY['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'],
    116,
    'movie',
    ARRAY['aliens', 'language', 'communication', 'time'],
    ARRAY['scifi']
),
(
    'Ex Machina',
    'A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a highly advanced humanoid A.I.',
    2014,
    7.7,
    'https://image.tmdb.org/t/p/w500/pmAv14TPE2vKMIRrVeCd1Ll7K94.jpg',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    'vKQi3bBA1y8',
    'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    ARRAY['Sci-Fi', 'Thriller'],
    'Alex Garland',
    ARRAY['Domhnall Gleeson', 'Alicia Vikander', 'Oscar Isaac'],
    108,
    'movie',
    ARRAY['ai', 'artificial intelligence', 'robot', 'turing test'],
    ARRAY['scifi']
),

-- AWARD WINNERS
(
    'Parasite',
    'A poor family schemes to become employed by a wealthy family and infiltrate their household by posing as unrelated, highly qualified individuals.',
    2019,
    8.5,
    'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    'https://www.youtube.com/watch?v=5xH0HfJHsaY',
    '5xH0HfJHsaY',
    'https://www.youtube.com/watch?v=5xH0HfJHsaY',
    ARRAY['Thriller', 'Drama', 'Comedy'],
    'Bong Joon-ho',
    ARRAY['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik', 'Park So-dam'],
    132,
    'movie',
    ARRAY['class', 'society', 'family', 'deception'],
    ARRAY['awardWinners']
),
(
    'Green Book',
    'A working-class Italian-American bouncer becomes the driver of an African-American classical pianist on a tour of venues through the 1960s American South.',
    2018,
    8.2,
    'https://image.tmdb.org/t/p/w500/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg',
    'https://www.youtube.com/watch?v=QkZxoko_HC0',
    'QkZxoko_HC0',
    'https://www.youtube.com/watch?v=QkZxoko_HC0',
    ARRAY['Biography', 'Comedy', 'Drama'],
    'Peter Farrelly',
    ARRAY['Viggo Mortensen', 'Mahershala Ali', 'Linda Cardellini', 'Sebastian Maniscalco'],
    130,
    'movie',
    ARRAY['racism', 'friendship', 'music', 'road trip'],
    ARRAY['awardWinners']
),
(
    'Moonlight',
    'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.',
    2016,
    7.4,
    'https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_SX300.jpg',
    'https://www.youtube.com/watch?v=9NJj12tJzqc',
    '9NJj12tJzqc',
    'https://www.youtube.com/watch?v=9NJj12tJzqc',
    ARRAY['Drama'],
    'Barry Jenkins',
    ARRAY['Trevante Rhodes', 'André Holland', 'Janelle Monáe', 'Ashton Sanders', 'Jharrel Jerome'],
    111,
    'movie',
    ARRAY['identity', 'sexuality', 'coming of age', 'african american'],
    ARRAY['awardWinners']
),
(
    'The Shape of Water',
    'At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.',
    2017,
    7.3,
    'https://image.tmdb.org/t/p/w500/k4FwHlMhuRR5BISY2Gm2QZHlH5Q.jpg',
    'https://www.youtube.com/watch?v=XFYWazblaUA',
    'XFYWazblaUA',
    'https://www.youtube.com/watch?v=XFYWazblaUA',
    ARRAY['Drama', 'Fantasy', 'Romance'],
    'Guillermo del Toro',
    ARRAY['Sally Hawkins', 'Michael Shannon', 'Richard Jenkins', 'Doug Jones', 'Michael Stuhlbarg'],
    123,
    'movie',
    ARRAY['love', 'creature', 'fantasy', 'romance'],
    ARRAY['awardWinners']
),

-- MODERN BLOCKBUSTERS
(
    'Avatar: The Way of Water',
    'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Navi race to protect their home.',
    2022,
    7.6,
    'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    'https://www.youtube.com/watch?v=d9MyW72ELq0',
    'd9MyW72ELq0',
    'https://www.youtube.com/watch?v=d9MyW72ELq0',
    ARRAY['Action', 'Adventure', 'Sci-Fi'],
    'James Cameron',
    ARRAY['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang', 'Kate Winslet'],
    192,
    'movie',
    ARRAY['avatar', 'pandora', 'navi', 'ocean'],
    ARRAY['modernBlockbusters', 'scifi']
),
(
    'Top Gun: Maverick',
    'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUNs elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.',
    2022,
    8.3,
    'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    'https://www.youtube.com/watch?v=qSqVVswa420',
    'qSqVVswa420',
    'https://www.youtube.com/watch?v=qSqVVswa420',
    ARRAY['Action', 'Drama'],
    'Joseph Kosinski',
    ARRAY['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm', 'Glen Powell'],
    130,
    'movie',
    ARRAY['aviation', 'military', 'sequel', 'action'],
    ARRAY['modernBlockbusters']
),
(
    'Spider-Man: No Way Home',
    'With Spider-Mans identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.',
    2021,
    8.2,
    'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    'https://www.youtube.com/watch?v=JfVOs4VSpmA',
    'JfVOs4VSpmA',
    'https://www.youtube.com/watch?v=JfVOs4VSpmA',
    ARRAY['Action', 'Adventure', 'Sci-Fi'],
    'Jon Watts',
    ARRAY['Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Jacob Batalon', 'Jon Favreau'],
    148,
    'movie',
    ARRAY['spider-man', 'multiverse', 'superhero', 'marvel'],
    ARRAY['modernBlockbusters', 'scifi']
),
(
    'Avengers: Endgame',
    'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos actions and restore balance to the universe.',
    2019,
    8.4,
    'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    'https://www.youtube.com/watch?v=TcMBFSGVi1c',
    'TcMBFSGVi1c',
    'https://www.youtube.com/watch?v=TcMBFSGVi1c',
    ARRAY['Action', 'Adventure', 'Drama'],
    'Anthony Russo, Joe Russo',
    ARRAY['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson'],
    181,
    'movie',
    ARRAY['avengers', 'marvel', 'superhero', 'finale'],
    ARRAY['modernBlockbusters']
),

-- Additional movies to fill out categories to 5 each
(
    'The Shawshank Redemption',
    'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    1994,
    9.3,
    'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    'https://www.youtube.com/watch?v=6hB3S9bIaco',
    '6hB3S9bIaco',
    'https://www.youtube.com/watch?v=6hB3S9bIaco',
    ARRAY['Drama'],
    'Frank Darabont',
    ARRAY['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler'],
    142,
    'movie',
    ARRAY['prison', 'hope', 'friendship', 'redemption'],
    ARRAY['trending']
),
(
    'Nomadland',
    'A woman in her sixties embarks on a journey through the western United States after losing everything in the Great Recession, living in a van and working seasonal jobs.',
    2020,
    7.3,
    'https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg',
    'https://www.youtube.com/watch?v=6sxCFZ8_d84',
    '6sxCFZ8_d84',
    'https://www.youtube.com/watch?v=6sxCFZ8_d84',
    ARRAY['Drama'],
    'Chloé Zhao',
    ARRAY['Frances McDormand', 'David Strathairn', 'Linda May', 'Charlene Swankie'],
    107,
    'movie',
    ARRAY['nomad', 'recession', 'journey', 'survival'],
    ARRAY['awardWinners']
);
